"""
report_md.py
============
Stage 10b: Generates a human-readable Markdown report summarizing the
revision analysis, suitable for sharing with engineers/reviewers or
embedding in a documentation repo / pull request description.
"""

from __future__ import annotations

from pathlib import Path
from typing import Any, Dict, Union

from config.config import settings
from modules.utils.logger import get_logger

logger = get_logger(__name__)

_CATEGORY_ICONS = {
    "ADDED": "🟢",
    "REMOVED": "🔴",
    "MODIFIED": "🟡",
    "DIMENSION_CHANGE": "🟡",
    "TEXT_CHANGE": "🟡",
    "GEOMETRY_CHANGE": "🔵",
}


def render_markdown_report(report: Dict[str, Any], annotated_image_relpath: str = "annotated_comparison.png") -> str:
    """
    Render a Markdown document string from a report dict produced by
    report_json.build_report_dict().
    """
    lines = []
    lines.append(f"# {report['report_title']}")
    lines.append("")
    lines.append(f"*Generated by {report['generated_by']} on {report['generated_at_utc']}*")
    lines.append("")
    lines.append("## Inputs")
    lines.append("")
    lines.append(f"- **Before drawing:** `{report['inputs']['before_pdf']}`")
    lines.append(f"- **After drawing:** `{report['inputs']['after_pdf']}`")
    lines.append("")
    lines.append("## Quality Metrics")
    lines.append("")
    qm = report["quality_metrics"]
    lines.append(f"- Global SSIM score: `{qm['global_ssim_score']}`")
    lines.append(f"- Alignment correlation: `{qm['alignment_correlation']}`")
    lines.append("")
    lines.append("## Summary")
    lines.append("")
    summary = report["summary"]
    lines.append(f"**Total changes detected: {summary['total_changes']}**")
    lines.append("")
    lines.append("| Category | Count |")
    lines.append("|---|---|")
    for category, count in summary["by_category"].items():
        icon = _CATEGORY_ICONS.get(category, "⚪")
        lines.append(f"| {icon} {category} | {count} |")
    lines.append("")
    lines.append(f"## Annotated Comparison\n")
    lines.append(f"![Annotated comparison]({annotated_image_relpath})")
    lines.append("")
    lines.append("## Detailed Change Log")
    lines.append("")
    lines.append("| # | Category | Confidence | Class | Before | After | Reasons |")
    lines.append("|---|---|---|---|---|---|---|")

    for change in report["changes"]:
        icon = _CATEGORY_ICONS.get(change["category"], "⚪")
        before_val = change["before_text"] or (str(change["before_value"]) if change["before_value"] is not None else "—")
        after_val = change["after_text"] or (str(change["after_value"]) if change["after_value"] is not None else "—")
        reasons = "; ".join(change["reasons"]) if change["reasons"] else "—"
        lines.append(
            f"| {change['id']} | {icon} {change['category']} | "
            f"{change['confidence'] * 100:.0f}% | {change['object_class']} | "
            f"{before_val} | {after_val} | {reasons} |"
        )

    lines.append("")
    lines.append("---")
    lines.append(f"*Report generated automatically. Review all high-impact changes with the responsible engineer before sign-off.*")

    return "\n".join(lines)


def save_markdown_report(report: Dict[str, Any], output_path: Union[str, Path], annotated_image_relpath: str = "annotated_comparison.png") -> str:
    output_path = Path(output_path)
    output_path.parent.mkdir(parents=True, exist_ok=True)
    markdown = render_markdown_report(report, annotated_image_relpath)
    with open(output_path, "w", encoding="utf-8") as f:
        f.write(markdown)
    logger.info("Markdown report saved to '%s'.", output_path)
    return str(output_path)
